<?php

namespace App\Tests\Unit;

use App\Entity\Candidate;
use App\Entity\Company;
use App\Entity\Job;
use App\Entity\Skill;
use App\Service\MatchingService;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class BasicTest extends KernelTestCase
{

    private $matchingService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $kernel = $this->bootKernel();
        $container = $kernel->getContainer();
        $this->matchingService = $container->get(MatchingService::class);

    }

    public function testSomething(): void
    {
        $this->assertTrue(true);
//1 create a company

        $result = $this->matchingService->foundMatching(0);

        self::assertEquals($result);
        //$results = $matchingService->match($jobs, $candidates);
        // assert que le resultat contient bien le jobX pour le candidat Y
        // verifier le résultat

        #new candidat/ new offre

        # appel service matching
    }
}